// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/burbble/marketplace/internal/exchange"
	"sync"
)

// Ensure, that RateProviderMock does implement exchange.RateProvider.
// If this is not the case, regenerate this file with moq.
var _ exchange.RateProvider = &RateProviderMock{}

// RateProviderMock is a mock implementation of exchange.RateProvider.
//
//	func TestSomethingThatUsesRateProvider(t *testing.T) {
//
//		// make and configure a mocked exchange.RateProvider
//		mockedRateProvider := &RateProviderMock{
//			GetUSDTRateFunc: func(ctx context.Context) (float64, error) {
//				panic("mock out the GetUSDTRate method")
//			},
//		}
//
//		// use mockedRateProvider in code that requires exchange.RateProvider
//		// and then make assertions.
//
//	}
type RateProviderMock struct {
	// GetUSDTRateFunc mocks the GetUSDTRate method.
	GetUSDTRateFunc func(ctx context.Context) (float64, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetUSDTRate holds details about calls to the GetUSDTRate method.
		GetUSDTRate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetUSDTRate sync.RWMutex
}

// GetUSDTRate calls GetUSDTRateFunc.
func (mock *RateProviderMock) GetUSDTRate(ctx context.Context) (float64, error) {
	if mock.GetUSDTRateFunc == nil {
		panic("RateProviderMock.GetUSDTRateFunc: method is nil but RateProvider.GetUSDTRate was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetUSDTRate.Lock()
	mock.calls.GetUSDTRate = append(mock.calls.GetUSDTRate, callInfo)
	mock.lockGetUSDTRate.Unlock()
	return mock.GetUSDTRateFunc(ctx)
}

// GetUSDTRateCalls gets all the calls that were made to GetUSDTRate.
// Check the length with:
//
//	len(mockedRateProvider.GetUSDTRateCalls())
func (mock *RateProviderMock) GetUSDTRateCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetUSDTRate.RLock()
	calls = mock.calls.GetUSDTRate
	mock.lockGetUSDTRate.RUnlock()
	return calls
}
