// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/burbble/marketplace/internal/domain"
	"github.com/burbble/marketplace/internal/repository/postgres"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that ProductRepositoryMock does implement postgres.ProductRepository.
// If this is not the case, regenerate this file with moq.
var _ postgres.ProductRepository = &ProductRepositoryMock{}

// ProductRepositoryMock is a mock implementation of postgres.ProductRepository.
//
//	func TestSomethingThatUsesProductRepository(t *testing.T) {
//
//		// make and configure a mocked postgres.ProductRepository
//		mockedProductRepository := &ProductRepositoryMock{
//			GetBrandsFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetBrands method")
//			},
//			GetByFilterFunc: func(ctx context.Context, filter domain.ProductFilter) (*domain.ProductList, error) {
//				panic("mock out the GetByFilter method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
//				panic("mock out the GetByID method")
//			},
//			UpsertFunc: func(ctx context.Context, products []domain.Product) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedProductRepository in code that requires postgres.ProductRepository
//		// and then make assertions.
//
//	}
type ProductRepositoryMock struct {
	// GetBrandsFunc mocks the GetBrands method.
	GetBrandsFunc func(ctx context.Context) ([]string, error)

	// GetByFilterFunc mocks the GetByFilter method.
	GetByFilterFunc func(ctx context.Context, filter domain.ProductFilter) (*domain.ProductList, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.Product, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(ctx context.Context, products []domain.Product) error

	// calls tracks calls to the methods.
	calls struct {
		// GetBrands holds details about calls to the GetBrands method.
		GetBrands []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByFilter holds details about calls to the GetByFilter method.
		GetByFilter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter domain.ProductFilter
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Products is the products argument value.
			Products []domain.Product
		}
	}
	lockGetBrands   sync.RWMutex
	lockGetByFilter sync.RWMutex
	lockGetByID     sync.RWMutex
	lockUpsert      sync.RWMutex
}

// GetBrands calls GetBrandsFunc.
func (mock *ProductRepositoryMock) GetBrands(ctx context.Context) ([]string, error) {
	if mock.GetBrandsFunc == nil {
		panic("ProductRepositoryMock.GetBrandsFunc: method is nil but ProductRepository.GetBrands was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetBrands.Lock()
	mock.calls.GetBrands = append(mock.calls.GetBrands, callInfo)
	mock.lockGetBrands.Unlock()
	return mock.GetBrandsFunc(ctx)
}

// GetBrandsCalls gets all the calls that were made to GetBrands.
// Check the length with:
//
//	len(mockedProductRepository.GetBrandsCalls())
func (mock *ProductRepositoryMock) GetBrandsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetBrands.RLock()
	calls = mock.calls.GetBrands
	mock.lockGetBrands.RUnlock()
	return calls
}

// GetByFilter calls GetByFilterFunc.
func (mock *ProductRepositoryMock) GetByFilter(ctx context.Context, filter domain.ProductFilter) (*domain.ProductList, error) {
	if mock.GetByFilterFunc == nil {
		panic("ProductRepositoryMock.GetByFilterFunc: method is nil but ProductRepository.GetByFilter was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter domain.ProductFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetByFilter.Lock()
	mock.calls.GetByFilter = append(mock.calls.GetByFilter, callInfo)
	mock.lockGetByFilter.Unlock()
	return mock.GetByFilterFunc(ctx, filter)
}

// GetByFilterCalls gets all the calls that were made to GetByFilter.
// Check the length with:
//
//	len(mockedProductRepository.GetByFilterCalls())
func (mock *ProductRepositoryMock) GetByFilterCalls() []struct {
	Ctx    context.Context
	Filter domain.ProductFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter domain.ProductFilter
	}
	mock.lockGetByFilter.RLock()
	calls = mock.calls.GetByFilter
	mock.lockGetByFilter.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *ProductRepositoryMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	if mock.GetByIDFunc == nil {
		panic("ProductRepositoryMock.GetByIDFunc: method is nil but ProductRepository.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedProductRepository.GetByIDCalls())
func (mock *ProductRepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *ProductRepositoryMock) Upsert(ctx context.Context, products []domain.Product) error {
	if mock.UpsertFunc == nil {
		panic("ProductRepositoryMock.UpsertFunc: method is nil but ProductRepository.Upsert was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Products []domain.Product
	}{
		Ctx:      ctx,
		Products: products,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(ctx, products)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedProductRepository.UpsertCalls())
func (mock *ProductRepositoryMock) UpsertCalls() []struct {
	Ctx      context.Context
	Products []domain.Product
} {
	var calls []struct {
		Ctx      context.Context
		Products []domain.Product
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}

// Ensure, that CategoryRepositoryMock does implement postgres.CategoryRepository.
// If this is not the case, regenerate this file with moq.
var _ postgres.CategoryRepository = &CategoryRepositoryMock{}

// CategoryRepositoryMock is a mock implementation of postgres.CategoryRepository.
//
//	func TestSomethingThatUsesCategoryRepository(t *testing.T) {
//
//		// make and configure a mocked postgres.CategoryRepository
//		mockedCategoryRepository := &CategoryRepositoryMock{
//			GetAllFunc: func(ctx context.Context) ([]domain.Category, error) {
//				panic("mock out the GetAll method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*domain.Category, error) {
//				panic("mock out the GetByID method")
//			},
//			GetBySlugFunc: func(ctx context.Context, slug string) (*domain.Category, error) {
//				panic("mock out the GetBySlug method")
//			},
//			UpsertFunc: func(ctx context.Context, categories []domain.Category) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedCategoryRepository in code that requires postgres.CategoryRepository
//		// and then make assertions.
//
//	}
type CategoryRepositoryMock struct {
	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) ([]domain.Category, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.Category, error)

	// GetBySlugFunc mocks the GetBySlug method.
	GetBySlugFunc func(ctx context.Context, slug string) (*domain.Category, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(ctx context.Context, categories []domain.Category) error

	// calls tracks calls to the methods.
	calls struct {
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetBySlug holds details about calls to the GetBySlug method.
		GetBySlug []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Slug is the slug argument value.
			Slug string
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Categories is the categories argument value.
			Categories []domain.Category
		}
	}
	lockGetAll    sync.RWMutex
	lockGetByID   sync.RWMutex
	lockGetBySlug sync.RWMutex
	lockUpsert    sync.RWMutex
}

// GetAll calls GetAllFunc.
func (mock *CategoryRepositoryMock) GetAll(ctx context.Context) ([]domain.Category, error) {
	if mock.GetAllFunc == nil {
		panic("CategoryRepositoryMock.GetAllFunc: method is nil but CategoryRepository.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedCategoryRepository.GetAllCalls())
func (mock *CategoryRepositoryMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *CategoryRepositoryMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.Category, error) {
	if mock.GetByIDFunc == nil {
		panic("CategoryRepositoryMock.GetByIDFunc: method is nil but CategoryRepository.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedCategoryRepository.GetByIDCalls())
func (mock *CategoryRepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetBySlug calls GetBySlugFunc.
func (mock *CategoryRepositoryMock) GetBySlug(ctx context.Context, slug string) (*domain.Category, error) {
	if mock.GetBySlugFunc == nil {
		panic("CategoryRepositoryMock.GetBySlugFunc: method is nil but CategoryRepository.GetBySlug was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Slug string
	}{
		Ctx:  ctx,
		Slug: slug,
	}
	mock.lockGetBySlug.Lock()
	mock.calls.GetBySlug = append(mock.calls.GetBySlug, callInfo)
	mock.lockGetBySlug.Unlock()
	return mock.GetBySlugFunc(ctx, slug)
}

// GetBySlugCalls gets all the calls that were made to GetBySlug.
// Check the length with:
//
//	len(mockedCategoryRepository.GetBySlugCalls())
func (mock *CategoryRepositoryMock) GetBySlugCalls() []struct {
	Ctx  context.Context
	Slug string
} {
	var calls []struct {
		Ctx  context.Context
		Slug string
	}
	mock.lockGetBySlug.RLock()
	calls = mock.calls.GetBySlug
	mock.lockGetBySlug.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *CategoryRepositoryMock) Upsert(ctx context.Context, categories []domain.Category) error {
	if mock.UpsertFunc == nil {
		panic("CategoryRepositoryMock.UpsertFunc: method is nil but CategoryRepository.Upsert was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Categories []domain.Category
	}{
		Ctx:        ctx,
		Categories: categories,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(ctx, categories)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedCategoryRepository.UpsertCalls())
func (mock *CategoryRepositoryMock) UpsertCalls() []struct {
	Ctx        context.Context
	Categories []domain.Category
} {
	var calls []struct {
		Ctx        context.Context
		Categories []domain.Category
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
