// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/burbble/marketplace/internal/domain"
	"github.com/burbble/marketplace/internal/service"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that ProductServiceMock does implement service.ProductService.
// If this is not the case, regenerate this file with moq.
var _ service.ProductService = &ProductServiceMock{}

// ProductServiceMock is a mock implementation of service.ProductService.
//
//	func TestSomethingThatUsesProductService(t *testing.T) {
//
//		// make and configure a mocked service.ProductService
//		mockedProductService := &ProductServiceMock{
//			GetBrandsFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetBrands method")
//			},
//			GetByFilterFunc: func(ctx context.Context, filter domain.ProductFilter) (*domain.ProductList, error) {
//				panic("mock out the GetByFilter method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
//				panic("mock out the GetByID method")
//			},
//		}
//
//		// use mockedProductService in code that requires service.ProductService
//		// and then make assertions.
//
//	}
type ProductServiceMock struct {
	// GetBrandsFunc mocks the GetBrands method.
	GetBrandsFunc func(ctx context.Context) ([]string, error)

	// GetByFilterFunc mocks the GetByFilter method.
	GetByFilterFunc func(ctx context.Context, filter domain.ProductFilter) (*domain.ProductList, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.Product, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetBrands holds details about calls to the GetBrands method.
		GetBrands []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByFilter holds details about calls to the GetByFilter method.
		GetByFilter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter domain.ProductFilter
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockGetBrands   sync.RWMutex
	lockGetByFilter sync.RWMutex
	lockGetByID     sync.RWMutex
}

// GetBrands calls GetBrandsFunc.
func (mock *ProductServiceMock) GetBrands(ctx context.Context) ([]string, error) {
	if mock.GetBrandsFunc == nil {
		panic("ProductServiceMock.GetBrandsFunc: method is nil but ProductService.GetBrands was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetBrands.Lock()
	mock.calls.GetBrands = append(mock.calls.GetBrands, callInfo)
	mock.lockGetBrands.Unlock()
	return mock.GetBrandsFunc(ctx)
}

// GetBrandsCalls gets all the calls that were made to GetBrands.
// Check the length with:
//
//	len(mockedProductService.GetBrandsCalls())
func (mock *ProductServiceMock) GetBrandsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetBrands.RLock()
	calls = mock.calls.GetBrands
	mock.lockGetBrands.RUnlock()
	return calls
}

// GetByFilter calls GetByFilterFunc.
func (mock *ProductServiceMock) GetByFilter(ctx context.Context, filter domain.ProductFilter) (*domain.ProductList, error) {
	if mock.GetByFilterFunc == nil {
		panic("ProductServiceMock.GetByFilterFunc: method is nil but ProductService.GetByFilter was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter domain.ProductFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetByFilter.Lock()
	mock.calls.GetByFilter = append(mock.calls.GetByFilter, callInfo)
	mock.lockGetByFilter.Unlock()
	return mock.GetByFilterFunc(ctx, filter)
}

// GetByFilterCalls gets all the calls that were made to GetByFilter.
// Check the length with:
//
//	len(mockedProductService.GetByFilterCalls())
func (mock *ProductServiceMock) GetByFilterCalls() []struct {
	Ctx    context.Context
	Filter domain.ProductFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter domain.ProductFilter
	}
	mock.lockGetByFilter.RLock()
	calls = mock.calls.GetByFilter
	mock.lockGetByFilter.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *ProductServiceMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	if mock.GetByIDFunc == nil {
		panic("ProductServiceMock.GetByIDFunc: method is nil but ProductService.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedProductService.GetByIDCalls())
func (mock *ProductServiceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// Ensure, that CategoryServiceMock does implement service.CategoryService.
// If this is not the case, regenerate this file with moq.
var _ service.CategoryService = &CategoryServiceMock{}

// CategoryServiceMock is a mock implementation of service.CategoryService.
//
//	func TestSomethingThatUsesCategoryService(t *testing.T) {
//
//		// make and configure a mocked service.CategoryService
//		mockedCategoryService := &CategoryServiceMock{
//			GetAllFunc: func(ctx context.Context) ([]domain.Category, error) {
//				panic("mock out the GetAll method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*domain.Category, error) {
//				panic("mock out the GetByID method")
//			},
//		}
//
//		// use mockedCategoryService in code that requires service.CategoryService
//		// and then make assertions.
//
//	}
type CategoryServiceMock struct {
	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) ([]domain.Category, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.Category, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockGetAll  sync.RWMutex
	lockGetByID sync.RWMutex
}

// GetAll calls GetAllFunc.
func (mock *CategoryServiceMock) GetAll(ctx context.Context) ([]domain.Category, error) {
	if mock.GetAllFunc == nil {
		panic("CategoryServiceMock.GetAllFunc: method is nil but CategoryService.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedCategoryService.GetAllCalls())
func (mock *CategoryServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *CategoryServiceMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.Category, error) {
	if mock.GetByIDFunc == nil {
		panic("CategoryServiceMock.GetByIDFunc: method is nil but CategoryService.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedCategoryService.GetByIDCalls())
func (mock *CategoryServiceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}
